### ISSUE TITLE
can‘t  retrieve the CDATA text

### ISSUE THREAD

**Issue by hi-linus** [SamDecrock/node-xmlreader#1]
I fix it by following code 
saxparser.oncdata = function(cdata){
    // add the function text() to the object to return the cdata value:
    object.text = function(){
        return cdata;
    }
};

saxparser.ontext = function (text) {
    // add the function text() to the object to return the text value:
    !object.text ? object.text = function(){
        return text;
    } : null;
};

**Comment by SamDecrock** [comment]
thx, I added your code!
