### ISSUE TITLE
Root node with a dot 

### ISSUE THREAD

**Issue by s4reea** [SamDecrock/node-xmlreader#4]
The xml file i am trying to fetch has "site.com" as a root node(without ""). 
I dont know how to put the right path using this tool
I am new to JS.

**Comment by sdb1228** [comment]
I was wondering if this was ever solved.  I also have a node that has a : and was wondering the best way to handle this.

**Comment by SamDecrock** [comment]
In JavaScript, dots (.) are used to access underlying objects. So `site.com` would result in accessing the object `com` inside the object `site`:

``` javascript
{
  site: {
    com: "some content"
  }
}
```

Which is obviously not what you want.

To surcome this annoyance, you can access objects in another way using square brackets and a string-notation:

``` javascript
["site.com"]
```

So to access the root-object `site.com`, you'll have to type

``` javascript
res["site.come"]
```

Then you can continue your way down the XML tree using the regular dot notation:

``` javascript
res["site.com"].anothernode.yetanothernode
```

or the bracket-string notation:

``` javascript
res["site.com"]["anothernode"]["yetanothernode"]
```

or a combination of both

``` javascript
res["site.com"].anothernode["yetanothernode"]
```

Have fun ;-)
