### ISSUE TITLE
read the encoding tag

### ISSUE THREAD

**Issue by thebergamo** [SamDecrock/node-xmlreader#6]
Hi!
I'm using the node-xmlreader, I try get a XML but the encoding charset sometimes is wrong.

If the modules read that information like: 

<?xml version="1.0" encoding="ISO-8859-1" ?>

I thinks it's very helpful to when we using to read a node.text() the text ever have a value without unknow chars.

**Comment by gorockymin** [comment]
if(res.feed){
}

**Comment by thebergamo** [comment]
I really don't remeber why I open this issue :p
