### ISSUE TITLE
Attributes with hyphen

### ISSUE THREAD

**Issue by AshwiniChalla** [SamDecrock/node-xmlreader#8]
I have some attibutes with - like "lines-covered" node.attributes().lines-covered doesnt work. How can I read the value of such attributes?

**Comment by SamDecrock** [comment]
that's because it's executing `node.attributes().lines` minus `covered` which probably doesn't yield a number ;-)

This is a classic javascript problem which can be solved by accessing attributes as strings like this:

``` js
node.attributes()["lines-covered"]
```
